[package]
name = "aqua_db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.56"
lru = "0.7.5"

[dev-dependencies]
tempfile = "3.3.0"
